export = {
    "assignments": 
	[{
        "fmv": null,
        "valuation_date": "2012-05-23",
        "company_name": "SoundCloud",
        "project_type": "asc718",
        "agg_value": null,
        "payment": "paid_full",
        "id": 10,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2010-12-31",
        "company_name": "BA Insight",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 15,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2013-07-03",
        "company_name": "roundCorner",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 19,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2013-05-13",
        "company_name": "Harry's",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 26,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": null,
        "company_name": "Players Tribune",
        "project_type": "409a",
        "agg_value": null,
        "payment": "no_tied_both",
        "id": 21,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2012-04-30",
        "company_name": "BA Insight",
        "project_type": "409a",
        "agg_value": null,
        "payment": null,
        "id": 16,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2014-06-30",
        "company_name": "Stack Exchange",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 7,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2011-02-28",
        "company_name": "Stack Exchange",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 3,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2014-01-20",
        "company_name": "Harry's",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 27,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2014-07-31",
        "company_name": "Address Report",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 22,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2012-01-31",
        "company_name": "Stack Exchange",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 4,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2013-03-31",
        "company_name": "BA Insight",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 17,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2013-01-02",
        "company_name": "Stack Exchange",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 5,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2010-05-31",
        "company_name": "Stack Exchange",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 2,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2013-04-30",
        "company_name": "Aetherpal",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 23,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": null,
        "company_name": "roundCorner",
        "project_type": "409a",
        "agg_value": null,
        "payment": "no_tied_both",
        "id": 20,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2013-04-30",
        "company_name": "SoundCloud",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 11,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2014-01-02",
        "company_name": "Stack Exchange",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 6,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2013-10-15",
        "company_name": "SoundCloud",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 12,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2012-03-31",
        "company_name": "Vox Media (SportsBLOGS, Inc.)",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 33,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2014-04-30",
        "company_name": "SoundCloud",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 14,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2010-12-31",
        "company_name": "SoundCloud",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 8,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2014-07-09",
        "company_name": "SoundCloud",
        "project_type": "other",
        "agg_value": null,
        "payment": "paid_full",
        "id": 13,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2013-06-30",
        "company_name": "BA Insight",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_draft",
        "id": 18,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2014-07-10",
        "company_name": "Trello",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 1,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2012-02-29",
        "company_name": "SoundCloud",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 9,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2014-05-31",
        "company_name": "Harry's",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 28,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2012-09-12",
        "company_name": "Harry's",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 25,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2013-10-25",
        "company_name": "Vox Media (SportsBLOGS, Inc.)",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 34,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2014-07-31",
        "company_name": "Alphaworks",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 32,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2011-07-22",
        "company_name": "Warby",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 35,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2011-09-30",
        "company_name": "Warby",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 36,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2011-01-31",
        "company_name": "Warby",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 37,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2012-07-24",
        "company_name": "Warby",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 38,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2013-01-15",
        "company_name": "Warby",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 39,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2011-12-31",
        "company_name": "Warby",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 40,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2013-06-30",
        "company_name": "Warby",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 41,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2013-12-17",
        "company_name": "Warby",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 42,
        "method": "financing"
    }, {
        "fmv": null,
        "valuation_date": "2014-09-30",
        "company_name": "Affinivax",
        "project_type": "409a",
        "agg_value": null,
        "payment": "paid_full",
        "id": 43,
        "method": "financing"
    }]
};